### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by andyli** [jdonaldson/promhx#57]
The implementation of [`Stream#first()`](https://github.com/jdonaldson/promhx/blob/master/src/main/promhx/Stream.hx#L133) looks like a memory leak to me, in the sense that the returned `Promise` can never be freed since it subscribes to the stream update forever.

In general, is there a way to unsubscribe?

**Comment by jdonaldson** [comment]
It's possible to unbind a stream, but it's not currently possible for a promise.

Keeping a promise bound is pretty useful, as it helps to catch situations where a promise resolves more than once (which can cause a lot of undesirable behavior, or expose a flaw in how you were trying to use the promise).  This can only work if the promise maintains a connection to its upstream resolver.

However, for practical purposes I do agree that it's useful to clear the memory after some point.  I think I'll relax some of the constraints on   Stream.detachStream so it can work with promises.

**Comment by jdonaldson** [comment]
In the future, you can use :

```haxe
some_async.unlink(some_other_async);
```

This will unlink the two asyncs.  Note that this operation (like the other link method) is asynchronous.

**Comment by jdonaldson** [comment]
also note, the use of unlink is not really recommended.
