### ISSUE TITLE
EventTools.eventStream return type should be Stream?

### ISSUE THREAD

**Issue by giabao** [jdonaldson/promhx#59]
[EventTools.eventStream](https://github.com/jdonaldson/promhx/blob/816341b1280b6da9f7299487ffa9ba08602d8e1b/src/main/promhx/haxe/EventTools.hx#L40)
`return def.promise();` should be `return def.stream();`?

**Comment by jdonaldson** [comment]
Fixed... I'll wait to update haxelib, there's some other pending changes there.
