### ISSUE TITLE
api documentation?

### ISSUE THREAD

**Issue by raould** [jdonaldson/promhx#64]
hi, is there fullish/completeish api documentation for promhx? Like, random example, I'm trying to see if there's anything like Bacon.js's interval() signal. Thanks.

**Comment by raould** [comment]
ok, for anybody else with similar questions, it looks like we're supposed to take advantage of the EventLoop? (still would be great if there were realish docs ;-)

**Comment by jdonaldson** [comment]
Yep, EventLoop is what you want, and yes, I totally didn't write any useful documentation for that, my bad.

I just wrote up a small example of how to manually specify a nextLoop method there in the Event Loop section of the readme.
