### ISSUE TITLE
examples? maybe on the wiki?

### ISSUE THREAD

**Issue by raould** [jdonaldson/promhx#65]
It would be great if people could populate the wiki with links to examples. I'm trying to learn both promhx and signal stuff all at the same time, so I'm easily confused. E.g. how to just do basic on click stuff using EventTools, I don't even know what the "callback" function arguments will be.

**Comment by jdonaldson** [comment]
I agree, although I htink a wiki would only be a slight improvement over a readme.  I'd really like to do something with try.haxe.org, and show the code actually working.  The whole lib is due for an update, imho.  There's a lot of things in haxe 3.2 that will make things a bit easier.  Once I'm done with my other super secret haxe project I'll give promhx some more love.

**Comment by jdonaldson** [comment]
Also, thanks for trying promhx!  And dealing with the warts!
